# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vavabot_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 461)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/icon_noctuline_wall_e_eve_hedge.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_credentials = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tab_credentials.setFont(font)
        self.tab_credentials.setObjectName("tab_credentials")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_credentials)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2_credentials = QtWidgets.QFrame(self.tab_credentials)
        self.frame_2_credentials.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2_credentials.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2_credentials.setObjectName("frame_2_credentials")
        self.label = QtWidgets.QLabel(self.frame_2_credentials)
        self.label.setGeometry(QtCore.QRect(60, 20, 111, 31))
        self.label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.lineEdit_api_key_new = QtWidgets.QLineEdit(self.frame_2_credentials)
        self.lineEdit_api_key_new.setGeometry(QtCore.QRect(10, 100, 171, 31))
        self.lineEdit_api_key_new.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEdit_api_key_new.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_api_key_new.setObjectName("lineEdit_api_key_new")
        self.label_2 = QtWidgets.QLabel(self.frame_2_credentials)
        self.label_2.setGeometry(QtCore.QRect(190, 70, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2_credentials)
        self.label_3.setGeometry(QtCore.QRect(190, 110, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_api_secret_saved = QtWidgets.QLineEdit(self.frame_2_credentials)
        self.lineEdit_api_secret_saved.setEnabled(True)
        self.lineEdit_api_secret_saved.setGeometry(QtCore.QRect(260, 60, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_api_secret_saved.setFont(font)
        self.lineEdit_api_secret_saved.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_api_secret_saved.setText("")
        self.lineEdit_api_secret_saved.setReadOnly(True)
        self.lineEdit_api_secret_saved.setObjectName("lineEdit_api_secret_saved")
        self.lineEdit_api_secret_new = QtWidgets.QLineEdit(self.frame_2_credentials)
        self.lineEdit_api_secret_new.setGeometry(QtCore.QRect(260, 100, 391, 31))
        self.lineEdit_api_secret_new.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEdit_api_secret_new.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_api_secret_new.setClearButtonEnabled(False)
        self.lineEdit_api_secret_new.setObjectName("lineEdit_api_secret_new")
        self.label_4 = QtWidgets.QLabel(self.frame_2_credentials)
        self.label_4.setGeometry(QtCore.QRect(350, 20, 111, 31))
        self.label_4.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.radioButton_testnet_true = QtWidgets.QRadioButton(self.frame_2_credentials)
        self.radioButton_testnet_true.setGeometry(QtCore.QRect(30, 280, 351, 17))
        self.radioButton_testnet_true.setObjectName("radioButton_testnet_true")
        self.radioButton_2_testnet_false = QtWidgets.QRadioButton(self.frame_2_credentials)
        self.radioButton_2_testnet_false.setGeometry(QtCore.QRect(30, 310, 321, 17))
        self.radioButton_2_testnet_false.setObjectName("radioButton_2_testnet_false")
        self.label_5 = QtWidgets.QLabel(self.frame_2_credentials)
        self.label_5.setGeometry(QtCore.QRect(20, 240, 201, 21))
        self.label_5.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.pushButton_submit_new_credintals = QtWidgets.QPushButton(self.frame_2_credentials)
        self.pushButton_submit_new_credintals.setGeometry(QtCore.QRect(430, 150, 231, 61))

        # password line edit and label created
        self.label_password = QtWidgets.QLabel(self.frame_2_credentials)
        self.label_password.setGeometry(QtCore.QRect(30, 145, 315, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.lineEdit_password = QtWidgets.QLineEdit(self.frame_2_credentials)
        self.lineEdit_password.setGeometry(QtCore.QRect(10, 173, 350, 31))
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_password.setClearButtonEnabled(False)
        self.lineEdit_password.setObjectName("lineEdit_password")
        # password line edit an label created - the end

        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_submit_new_credintals.setFont(font)
        self.pushButton_submit_new_credintals.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_submit_new_credintals.setObjectName("pushButton_submit_new_credintals")
        self.lineEdit_api_key_saved = QtWidgets.QLineEdit(self.frame_2_credentials)
        self.lineEdit_api_key_saved.setEnabled(True)
        self.lineEdit_api_key_saved.setGeometry(QtCore.QRect(10, 60, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_api_key_saved.setFont(font)
        self.lineEdit_api_key_saved.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_api_key_saved.setText("")
        self.lineEdit_api_key_saved.setReadOnly(True)
        self.lineEdit_api_key_saved.setObjectName("lineEdit_api_key_saved")
        self.lineEdit_testenet_true_or_false_satatus = QtWidgets.QLineEdit(self.frame_2_credentials)
        self.lineEdit_testenet_true_or_false_satatus.setGeometry(QtCore.QRect(230, 340, 113, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_testenet_true_or_false_satatus.setFont(font)
        self.lineEdit_testenet_true_or_false_satatus.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_testenet_true_or_false_satatus.setToolTipDuration(-1)
        self.lineEdit_testenet_true_or_false_satatus.setStyleSheet("color: rgb(255, 0, 0);")
        self.lineEdit_testenet_true_or_false_satatus.setText("")
        self.lineEdit_testenet_true_or_false_satatus.setCursorPosition(0)
        self.lineEdit_testenet_true_or_false_satatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_testenet_true_or_false_satatus.setDragEnabled(False)
        self.lineEdit_testenet_true_or_false_satatus.setReadOnly(True)
        self.lineEdit_testenet_true_or_false_satatus.setObjectName("lineEdit_testenet_true_or_false_satatus")
        self.label_7 = QtWidgets.QLabel(self.frame_2_credentials)
        self.label_7.setGeometry(QtCore.QRect(30, 339, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.line_4 = QtWidgets.QFrame(self.frame_2_credentials)
        self.line_4.setGeometry(QtCore.QRect(10, 220, 651, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.frame_2_credentials, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_credentials, "")
        self.tab_instruments = QtWidgets.QWidget()
        self.tab_instruments.setObjectName("tab_instruments")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_instruments)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_2 = QtWidgets.QFrame(self.tab_instruments)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setInputMethodHints(QtCore.Qt.ImhDate)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")

        self.lineEdit_orders_rate = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_orders_rate.setGeometry(QtCore.QRect(610, 185, 32, 20))
        self.lineEdit_orders_rate.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_orders_rate.setObjectName("lineEdit_orders_rate")

        self.pushButton_orders_rate = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_orders_rate.setGeometry(QtCore.QRect(591, 209, 70, 35))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_orders_rate.setFont(font)
        self.pushButton_orders_rate.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.pushButton_orders_rate.setObjectName("pushButton_submit_new_targets")

        self.pushButton_submit_new_instruments = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_submit_new_instruments.setGeometry(QtCore.QRect(420, 100, 231, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_submit_new_instruments.setFont(font)
        self.pushButton_submit_new_instruments.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_submit_new_instruments.setObjectName("pushButton_submit_new_instruments")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(10, 100, 311, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.textEdit_instruments_saved = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_instruments_saved.setGeometry(QtCore.QRect(10, 120, 311, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_instruments_saved.setFont(font)
        self.textEdit_instruments_saved.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEdit_instruments_saved.setReadOnly(True)
        self.textEdit_instruments_saved.setObjectName("textEdit_instruments_saved")
        self.line_5 = QtWidgets.QFrame(self.frame_2)
        self.line_5.setGeometry(QtCore.QRect(10, 161, 651, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 40, 651, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_currency_instrumet1 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.lineEdit_currency_instrumet1.setMinimumSize(QtCore.QSize(101, 0))
        self.lineEdit_currency_instrumet1.setObjectName("lineEdit_currency_instrumet1")
        self.lineEdit_currency_instrumet1.addItem("")
        self.lineEdit_currency_instrumet1.addItem("")
        self.lineEdit_currency_instrumet1.addItem("")
        self.horizontalLayout.addWidget(self.lineEdit_currency_instrumet1)
        self.lineEdit_maturity_instrumet1 = QtWidgets.QDateEdit(self.horizontalLayoutWidget)
        self.lineEdit_maturity_instrumet1.setMinimumSize(QtCore.QSize(64, 0))
        self.lineEdit_maturity_instrumet1.setStyleSheet("")
        self.lineEdit_maturity_instrumet1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit_maturity_instrumet1.setCalendarPopup(True)
        self.lineEdit_maturity_instrumet1.setTimeSpec(QtCore.Qt.LocalTime)
        self.lineEdit_maturity_instrumet1.setDate(QtCore.QDate(2021, 1, 1))
        self.lineEdit_maturity_instrumet1.setObjectName("lineEdit_maturity_instrumet1")
        self.horizontalLayout.addWidget(self.lineEdit_maturity_instrumet1)
        self.checkBox_perpetual_1 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_perpetual_1.setFont(font)
        self.checkBox_perpetual_1.setObjectName("checkBox_perpetual_1")
        self.horizontalLayout.addWidget(self.checkBox_perpetual_1)
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 651, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(30, 210, 196, 91))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setHorizontalSpacing(57)
        self.formLayout_3.setVerticalSpacing(1)
        self.formLayout_3.setObjectName("formLayout_3")
        self.comboBox_value_given_4 = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.comboBox_value_given_4.setMinimumSize(QtCore.QSize(105, 0))
        self.comboBox_value_given_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.comboBox_value_given_4.setObjectName("comboBox_value_given_4")
        self.comboBox_value_given_4.addItem("")
        self.comboBox_value_given_4.addItem("")
        self.comboBox_value_given_4.addItem("")
        self.comboBox_value_given_4.addItem("")
        self.comboBox_value_given_4.addItem("")
        self.comboBox_value_given_4.addItem("")
        self.comboBox_value_given_4.addItem("")
        self.comboBox_value_given_4.setItemText(6, "")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.comboBox_value_given_4)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_currency_exchange_rate_for_upper_and_lower1_2 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_currency_exchange_rate_for_upper_and_lower1_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_currency_exchange_rate_for_upper_and_lower1_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_currency_exchange_rate_for_upper_and_lower1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_currency_exchange_rate_for_upper_and_lower1_2.setObjectName("lineEdit_currency_exchange_rate_for_upper_and_lower1_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_currency_exchange_rate_for_upper_and_lower1_2)
        self.label_32 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_32.setObjectName("label_32")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.lineEdit_currency_exchange_rate_upper1_2 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_currency_exchange_rate_upper1_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_currency_exchange_rate_upper1_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_currency_exchange_rate_upper1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_currency_exchange_rate_upper1_2.setObjectName("lineEdit_currency_exchange_rate_upper1_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_currency_exchange_rate_upper1_2)
        self.label_33 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_33.setObjectName("label_33")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.lineEdit_currency_exchange_rate_lower1_3 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.lineEdit_currency_exchange_rate_lower1_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_currency_exchange_rate_lower1_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_currency_exchange_rate_lower1_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_currency_exchange_rate_lower1_3.setObjectName("lineEdit_currency_exchange_rate_lower1_3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_currency_exchange_rate_lower1_3)
        self.textEdit_instruments_saved_2 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_instruments_saved_2.setGeometry(QtCore.QRect(360, 270, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_instruments_saved_2.setFont(font)
        self.textEdit_instruments_saved_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEdit_instruments_saved_2.setReadOnly(True)
        self.textEdit_instruments_saved_2.setObjectName("textEdit_instruments_saved_2")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(360, 240, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.pushButton_submit_new_instruments_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_submit_new_instruments_2.setGeometry(QtCore.QRect(30, 310, 191, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_submit_new_instruments_2.setFont(font)
        self.pushButton_submit_new_instruments_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_submit_new_instruments_2.setObjectName("pushButton_submit_new_instruments_2")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(30, 180, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(230, 250, 80, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(230, 270, 80, 21))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_10.raise_()
        self.label_17.raise_()
        self.textEdit_instruments_saved.raise_()
        self.line_5.raise_()
        self.horizontalLayoutWidget.raise_()
        self.pushButton_submit_new_instruments.raise_()

        self.pushButton_orders_rate.raise_()

        self.label_8.raise_()
        self.formLayoutWidget_3.raise_()
        self.textEdit_instruments_saved_2.raise_()
        self.label_18.raise_()
        self.pushButton_submit_new_instruments_2.raise_()
        self.label_6.raise_()
        self.label_11.raise_()
        self.gridLayout_6.addWidget(self.frame_2, 0, 0, 2, 1)
        self.tabWidget.addTab(self.tab_instruments, "")
        self.tab_targets = QtWidgets.QWidget()
        self.tab_targets.setObjectName("tab_targets")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_targets)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_4_targets = QtWidgets.QFrame(self.tab_targets)
        self.frame_4_targets.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4_targets.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4_targets.setObjectName("frame_4_targets")
        self.textEdit_balance = QtWidgets.QTextEdit(self.frame_4_targets)
        self.textEdit_balance.setGeometry(QtCore.QRect(10, 50, 291, 321))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_balance.setFont(font)
        self.textEdit_balance.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEdit_balance.setReadOnly(True)
        self.textEdit_balance.setObjectName("textEdit_balance")
        self.label_42 = QtWidgets.QLabel(self.frame_4_targets)
        self.label_42.setGeometry(QtCore.QRect(10, 20, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_42.setObjectName("label_42")
        self.pushButton_update_balance = QtWidgets.QPushButton(self.frame_4_targets)
        self.pushButton_update_balance.setGeometry(QtCore.QRect(310, 180, 71, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_update_balance.setFont(font)
        self.pushButton_update_balance.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_update_balance.setObjectName("pushButton_update_balance")
        self.textEdit_balance_after = QtWidgets.QTextEdit(self.frame_4_targets)
        self.textEdit_balance_after.setGeometry(QtCore.QRect(390, 50, 271, 321))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_balance_after.setFont(font)
        self.textEdit_balance_after.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEdit_balance_after.setReadOnly(True)
        self.textEdit_balance_after.setObjectName("textEdit_balance_after")
        self.label_43 = QtWidgets.QLabel(self.frame_4_targets)
        self.label_43.setGeometry(QtCore.QRect(390, 20, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.frame_4_targets, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_targets, "")
        self.tab_run_trading = QtWidgets.QWidget()
        self.tab_run_trading.setObjectName("tab_run_trading")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_run_trading)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_3_run_trade = QtWidgets.QFrame(self.tab_run_trading)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frame_3_run_trade.setFont(font)
        self.frame_3_run_trade.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3_run_trade.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3_run_trade.setObjectName("frame_3_run_trade")
        self.textEdit_monitor = QtWidgets.QTextEdit(self.frame_3_run_trade)
        self.textEdit_monitor.setGeometry(QtCore.QRect(3, 140, 511, 231))
        self.textEdit_monitor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEdit_monitor.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.textEdit_monitor.setUndoRedoEnabled(True)
        self.textEdit_monitor.setReadOnly(True)
        self.textEdit_monitor.setObjectName("textEdit_monitor")
        self.label_41 = QtWidgets.QLabel(self.frame_3_run_trade)
        self.label_41.setGeometry(QtCore.QRect(10, 100, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_41.setObjectName("label_41")
        self.pushButton_start_trading = QtWidgets.QPushButton(self.frame_3_run_trade)
        self.pushButton_start_trading.setGeometry(QtCore.QRect(0, 40, 141, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_start_trading.setFont(font)
        self.pushButton_start_trading.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(49, 148, 72);")
        self.pushButton_start_trading.setObjectName("pushButton_start_trading")
        self.pushButton_start_print_loglog = QtWidgets.QPushButton(self.frame_3_run_trade)
        self.pushButton_start_print_loglog.setGeometry(QtCore.QRect(40, 110, 75, 23))
        self.pushButton_start_print_loglog.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_start_print_loglog.setCheckable(False)
        self.pushButton_start_print_loglog.setObjectName("pushButton_start_print_loglog")
        self.lineEdit_24_btc_index = QtWidgets.QLineEdit(self.frame_3_run_trade)
        self.lineEdit_24_btc_index.setGeometry(QtCore.QRect(590, 30, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_24_btc_index.setFont(font)
        self.lineEdit_24_btc_index.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_24_btc_index.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_24_btc_index.setReadOnly(True)
        self.lineEdit_24_btc_index.setObjectName("lineEdit_24_btc_index")
        self.label_22 = QtWidgets.QLabel(self.frame_3_run_trade)
        self.label_22.setGeometry(QtCore.QRect(520, 30, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayoutWidget_10 = QtWidgets.QWidget(self.frame_3_run_trade)
        self.formLayoutWidget_10.setGeometry(QtCore.QRect(520, 80, 141, 126))
        self.formLayoutWidget_10.setObjectName("formLayoutWidget_10")
        self.formLayout_10 = QtWidgets.QFormLayout(self.formLayoutWidget_10)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.lineEdit_24.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_24.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_24.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_24.setReadOnly(True)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_24)
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.lineEdit_25.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_25.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_25.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_25.setReadOnly(True)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_25)
        self.label_26 = QtWidgets.QLabel(self.formLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.lineEdit_26.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_26.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_26.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_26.setReadOnly(True)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_26)
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget_10)
        self.label_30.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.formLayout_10.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.lineEdit_27.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_27.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_27.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_27.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_27.setReadOnly(True)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_27)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.formLayoutWidget_10)
        self.lineEdit_28.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_28.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_28.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_28.setReadOnly(True)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.formLayout_10.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_28)
        self.label_44 = QtWidgets.QLabel(self.frame_3_run_trade)
        self.label_44.setGeometry(QtCore.QRect(520, 60, 141, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.lineEdit_58 = QtWidgets.QLineEdit(self.frame_3_run_trade)
        self.lineEdit_58.setGeometry(QtCore.QRect(620, 0, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_58.setFont(font)
        self.lineEdit_58.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.pushButton = QtWidgets.QPushButton(self.frame_3_run_trade)
        self.pushButton.setGeometry(QtCore.QRect(420, 50, 91, 51))
        self.pushButton.setObjectName("pushButton")
        self.line = QtWidgets.QFrame(self.frame_3_run_trade)
        self.line.setGeometry(QtCore.QRect(520, 205, 141, 16))
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayoutWidget_11 = QtWidgets.QWidget(self.frame_3_run_trade)
        self.formLayoutWidget_11.setGeometry(QtCore.QRect(520, 220, 142, 152))
        self.formLayoutWidget_11.setObjectName("formLayoutWidget_11")
        self.formLayout_11 = QtWidgets.QFormLayout(self.formLayoutWidget_11)
        self.formLayout_11.setContentsMargins(0, 0, 0, 0)
        self.formLayout_11.setObjectName("formLayout_11")
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.lineEdit_29.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_29.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_29.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_29.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_29.setReadOnly(True)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_29)
        self.label_27 = QtWidgets.QLabel(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.lineEdit_30.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_30.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_30.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_30.setReadOnly(True)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_30)
        self.label_28 = QtWidgets.QLabel(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.lineEdit_31.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_31.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_31.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_31.setReadOnly(True)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_31)
        self.label_35 = QtWidgets.QLabel(self.formLayoutWidget_11)
        self.label_35.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.label_36 = QtWidgets.QLabel(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.formLayout_11.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.lineEdit_32.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_32.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_32.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_32.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_32.setReadOnly(True)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.formLayout_11.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_32)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.lineEdit_33.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_33.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_33.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_33.setReadOnly(True)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.formLayout_11.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_33)
        self.label_37 = QtWidgets.QLabel(self.formLayoutWidget_11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.formLayout_11.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.formLayoutWidget_11)
        self.lineEdit_34.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_34.setSizeIncrement(QtCore.QSize(50, 0))
        self.lineEdit_34.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_34.setReadOnly(True)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.formLayout_11.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_34)
        self.label_24 = QtWidgets.QLabel(self.frame_3_run_trade)
        self.label_24.setGeometry(QtCore.QRect(10, 10, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.pushButton_stop_arbitrage = QtWidgets.QPushButton(self.frame_3_run_trade)
        self.pushButton_stop_arbitrage.setGeometry(QtCore.QRect(220, 40, 75, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_stop_arbitrage.setFont(font)
        self.pushButton_stop_arbitrage.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_stop_arbitrage.setStyleSheet("color: rgb(255, 0, 0);")
        self.pushButton_stop_arbitrage.setCheckable(False)
        self.pushButton_stop_arbitrage.setObjectName("pushButton_stop_arbitrage")
        self.label_29 = QtWidgets.QLabel(self.frame_3_run_trade)
        self.label_29.setGeometry(QtCore.QRect(80, 10, 21, 21))
        self.label_29.setText("")
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.label_34 = QtWidgets.QLabel(self.frame_3_run_trade)
        self.label_34.setGeometry(QtCore.QRect(147, 60, 21, 21))
        self.label_34.setText("")
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName("label_34")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3_run_trade)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 10, 20, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox_autoScrollBar = QtWidgets.QCheckBox(self.frame_3_run_trade)
        self.checkBox_autoScrollBar.setGeometry(QtCore.QRect(420, 120, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_autoScrollBar.setFont(font)
        self.checkBox_autoScrollBar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_autoScrollBar.setObjectName("checkBox_autoScrollBar")
        self.label_41.raise_()
        self.label_22.raise_()
        self.textEdit_monitor.raise_()
        self.pushButton_start_trading.raise_()
        self.pushButton_start_print_loglog.raise_()
        self.lineEdit_24_btc_index.raise_()
        self.formLayoutWidget_10.raise_()
        self.label_44.raise_()
        self.lineEdit_58.raise_()
        self.pushButton.raise_()
        self.line.raise_()
        self.formLayoutWidget_11.raise_()
        self.label_24.raise_()
        self.pushButton_stop_arbitrage.raise_()
        self.label_29.raise_()
        self.label_34.raise_()
        self.pushButton_2.raise_()
        self.checkBox_autoScrollBar.raise_()
        self.gridLayout_4.addWidget(self.frame_3_run_trade, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_run_trading, "")

        # Tab About 1 - start
        self.tab_about = QtWidgets.QWidget()
        self.tab_about.setObjectName("tab_about")
        self.frame_5_about = QtWidgets.QFrame(self.tab_about)
        self.frame_5_about.setGeometry(QtCore.QRect(10, 0, 666, 371))
        self.frame_5_about.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5_about.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5_about.setObjectName("frame_5_about")

        self.textEdit_license = QtWidgets.QTextEdit(self.frame_5_about)
        self.textEdit_license.setGeometry(QtCore.QRect(68, 196, 526, 175))
        self.textEdit_license.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                            "")
        self.textEdit_license.setUndoRedoEnabled(True)
        self.textEdit_license.setReadOnly(True)
        self.textEdit_license.setObjectName("textEdit_license")

        self.label_license = QtWidgets.QLabel(self.frame_5_about)
        self.label_license.setGeometry(QtCore.QRect(68, 164, 526, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_license.setFont(font)
        self.label_license.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.label_license.setObjectName("label_license")
        self.label_license.raise_()

        self.textEdit_contact_us = QtWidgets.QTextEdit(self.frame_5_about)
        self.textEdit_contact_us.setGeometry(QtCore.QRect(68, 5, 526, 56))
        self.textEdit_contact_us.setUndoRedoEnabled(True)
        self.textEdit_contact_us.setReadOnly(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.textEdit_contact_us.setFont(font)
        self.textEdit_contact_us.setObjectName("textEdit_contact_us")

        self.textEdit_buy_me_a_coffee = QtWidgets.QTextEdit(self.frame_5_about)
        self.textEdit_buy_me_a_coffee.setGeometry(QtCore.QRect(68, 62, 526, 112))
        self.textEdit_buy_me_a_coffee.setUndoRedoEnabled(True)
        self.textEdit_buy_me_a_coffee.setReadOnly(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.textEdit_buy_me_a_coffee.setFont(font)
        self.textEdit_buy_me_a_coffee.setObjectName("textEdit_buy_me_a_coffee")

        self.radioButton_agree = QtWidgets.QRadioButton(self.frame_5_about)
        self.radioButton_agree.setGeometry(QtCore.QRect(595, 320, 105, 14))
        self.radioButton_agree.setObjectName("radioButton_agree")

        self.radioButton_disagree = QtWidgets.QRadioButton(self.frame_5_about)
        self.radioButton_disagree.setGeometry(QtCore.QRect(595, 300, 105, 14))
        self.radioButton_disagree.setObjectName("radioButton_disagree")

        self.tabWidget.addTab(self.tab_about, "")
        # Tab About 1 - the end

        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        self.checkBox_perpetual_1.clicked['bool'].connect(self.lineEdit_maturity_instrumet1.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_api_key_new, self.lineEdit_api_secret_new)
        MainWindow.setTabOrder(self.lineEdit_api_secret_new, self.lineEdit_password)
        MainWindow.setTabOrder(self.lineEdit_password, self.pushButton_submit_new_credintals)
        MainWindow.setTabOrder(self.pushButton_submit_new_credintals, self.radioButton_testnet_true)
        MainWindow.setTabOrder(self.radioButton_testnet_true, self.radioButton_2_testnet_false)
        MainWindow.setTabOrder(self.radioButton_2_testnet_false, self.lineEdit_currency_instrumet1)
        MainWindow.setTabOrder(self.lineEdit_currency_instrumet1, self.lineEdit_maturity_instrumet1)
        MainWindow.setTabOrder(self.lineEdit_maturity_instrumet1, self.checkBox_perpetual_1)
        MainWindow.setTabOrder(self.checkBox_perpetual_1, self.pushButton_submit_new_instruments)
        MainWindow.setTabOrder(self.pushButton_submit_new_instruments, self.comboBox_value_given_4)
        MainWindow.setTabOrder(self.comboBox_value_given_4, self.lineEdit_currency_exchange_rate_for_upper_and_lower1_2)
        MainWindow.setTabOrder(self.lineEdit_currency_exchange_rate_for_upper_and_lower1_2, self.lineEdit_currency_exchange_rate_upper1_2)
        MainWindow.setTabOrder(self.lineEdit_currency_exchange_rate_upper1_2, self.lineEdit_currency_exchange_rate_lower1_3)
        MainWindow.setTabOrder(self.lineEdit_currency_exchange_rate_lower1_3, self.pushButton_submit_new_instruments_2)

        MainWindow.setTabOrder(self.pushButton_submit_new_instruments_2, self.lineEdit_orders_rate)
        MainWindow.setTabOrder(self.lineEdit_orders_rate, self.pushButton_orders_rate)

        MainWindow.setTabOrder(self.pushButton_orders_rate, self.pushButton_update_balance)
        MainWindow.setTabOrder(self.pushButton_update_balance, self.pushButton_start_trading)
        MainWindow.setTabOrder(self.pushButton_start_trading, self.pushButton_stop_arbitrage)
        MainWindow.setTabOrder(self.pushButton_stop_arbitrage, self.checkBox_autoScrollBar)
        MainWindow.setTabOrder(self.checkBox_autoScrollBar, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)

        MainWindow.setTabOrder(self.pushButton_2, self.radioButton_disagree)
        MainWindow.setTabOrder(self.radioButton_disagree, self.radioButton_agree)

        MainWindow.setTabOrder(self.radioButton_agree, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VavaBot - Delta Hedge"))
        self.label.setText(_translate("MainWindow", "API Key"))
        self.label_2.setText(_translate("MainWindow", "Salved"))
        self.label_3.setText(_translate("MainWindow", "Update"))
        self.label_4.setText(_translate("MainWindow", "API Secret"))

        self.label_password.setText(_translate("MainWindow", "Type password to recover API credentials:"))

        self.radioButton_testnet_true.setText(_translate("MainWindow", "TEST ACCOUNT"))
        self.radioButton_2_testnet_false.setText(_translate("MainWindow", "REAL ACCOUNT"))
        self.label_5.setText(_translate("MainWindow", "Select acoount mode:"))
        self.pushButton_submit_new_credintals.setText(_translate("MainWindow", "SUBMIT new Credentials"))
        self.label_7.setText(_translate("MainWindow", "Current Status account mode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_credentials), _translate("MainWindow", "Credentials"))
        self.pushButton_submit_new_instruments.setText(_translate("MainWindow", "UPDATE Instrument"))
        self.label_17.setText(_translate("MainWindow", "Check Saved Instruments:"))
        self.lineEdit_currency_instrumet1.setItemText(0, _translate("MainWindow", "Set BTC or ETH:"))
        self.lineEdit_currency_instrumet1.setItemText(1, _translate("MainWindow", "BTC"))
        self.lineEdit_currency_instrumet1.setItemText(2, _translate("MainWindow", "ETH"))
        self.lineEdit_maturity_instrumet1.setDisplayFormat(_translate("MainWindow", "dMMMyy"))
        self.checkBox_perpetual_1.setText(_translate("MainWindow", "PERPETUAL"))
        self.label_8.setText(_translate("MainWindow", "Instrument for hedge:"))
        self.comboBox_value_given_4.setItemText(0, _translate("MainWindow", "Set Hedge Method"))
        self.comboBox_value_given_4.setItemText(1, _translate("MainWindow", "Delta TOTAL "))
        self.comboBox_value_given_4.setItemText(2, _translate("MainWindow", "Options Delta"))
        self.comboBox_value_given_4.setItemText(3, _translate("MainWindow", "Options THETA "))
        self.comboBox_value_given_4.setItemText(4, _translate("MainWindow", "Options VEGA "))
        self.comboBox_value_given_4.setItemText(5, _translate("MainWindow", "Options GAMMA "))
        self.label_9.setText(_translate("MainWindow", "Hedge Target:"))
        self.lineEdit_currency_exchange_rate_for_upper_and_lower1_2.setText(_translate("MainWindow", "0"))
        self.label_32.setText(_translate("MainWindow", "SUPERIOR Limit:"))
        self.lineEdit_currency_exchange_rate_upper1_2.setText(_translate("MainWindow", "0.3"))
        self.label_33.setText(_translate("MainWindow", "INFERIOR Limit:"))
        self.lineEdit_currency_exchange_rate_lower1_3.setText(_translate("MainWindow", "0.3"))
        self.label_18.setText(_translate("MainWindow", "Check Saved Config:"))
        self.pushButton_submit_new_instruments_2.setText(_translate("MainWindow", "UPDATE Settings"))
        self.label_10.setText(_translate("MainWindow", "Settings:"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_orders_rate.setText(_translate("MainWindow", "Orders/sec\nUpdate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_instruments), _translate("MainWindow", "Config"))
        self.label_42.setText(_translate("MainWindow", "TOTAL Account Summary"))
        self.pushButton_update_balance.setText(_translate("MainWindow", "UPDATE\n"
" Balance"))
        self.label_43.setText(_translate("MainWindow", "OPTIONS Account Summary"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_targets), _translate("MainWindow", "Summary"))
        self.textEdit_monitor.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_41.setText(_translate("MainWindow", "Monitor"))
        self.pushButton_start_trading.setText(_translate("MainWindow", "START HEDGE"))
        self.pushButton_start_print_loglog.setText(_translate("MainWindow", "Start Print"))
        self.label_22.setText(_translate("MainWindow", "BTC Index:"))
        self.label_15.setText(_translate("MainWindow", "Delta Total"))
        self.label_25.setText(_translate("MainWindow", "Theta Options"))
        self.label_26.setText(_translate("MainWindow", "Delta Options"))
        self.label_30.setText(_translate("MainWindow", "Gamma Options"))
        self.label_31.setText(_translate("MainWindow", "Vega Options"))
        self.label_44.setText(_translate("MainWindow", "Account Summary"))
        self.pushButton.setText(_translate("MainWindow", "Request Index\n"
"and\n"
"Account Summary"))
        self.label_16.setText(_translate("MainWindow", "Currency"))
        self.label_27.setText(_translate("MainWindow", "Maint Margin"))
        self.label_28.setText(_translate("MainWindow", "Balance"))
        self.label_35.setText(_translate("MainWindow", "Total PL"))
        self.label_36.setText(_translate("MainWindow", "Futures PL"))
        self.label_37.setText(_translate("MainWindow", "Options PL"))
        self.label_24.setText(_translate("MainWindow", "Connection"))
        self.pushButton_stop_arbitrage.setText(_translate("MainWindow", "STOP\n"
"HEDGE"))
        self.pushButton_2.setText(_translate("MainWindow", "clear"))
        self.checkBox_autoScrollBar.setText(_translate("MainWindow", "Auto Scroll Bar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_run_trading), _translate("MainWindow", "Run Hedge"))

        # tab_about 2 start
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_about), _translate("MainWindow", "About"))
        self.label_license.setText(_translate("MainWindow", "License"))
        self.radioButton_agree.setText(_translate("MainWindow", "I Agree"))
        self.radioButton_disagree.setText(_translate("MainWindow", "I Disagree"))
        # tab_about 2 the end


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
